services:
  - type: web
    name: n8n
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    plan: starter
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: dpg-d7b4a2udqaus73c8dl30-a
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: n8ndb_j04a
      - key: DB_POSTGRESDB_USER
        value: n8ndb_j04a_user
      - key: DB_POSTGRESDB_PASSWORD
        value: Zlpc234aNDGfLnjyZC3UgEi9ex6B1CNz
      - key: N8N_ENCRYPTION_KEY
        value: GzfX8ZmGzB/6LGIVS91mMoIkiRi6c6aHlUR/frHqcZg=
      - key: N8N_HOST
        sync: false  # set manually in dashboard
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: 5678
      - key: PORT
        value: 5678
      - key: WEBHOOK_URL
        sync: false  # set manually in dashboard
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: TZ
        value: Europe/Paris
      - key: N8N_DEFAULT_LOCALE
        value: fr
